name: spec_cli
version: 0.1.2+2
description: CLI for Spec - a streamlined testing framework for Dart & Flutter.
homepage: "https://github.com/invertase/spec"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.1.1
  cli_util: ^0.3.0
  collection: ^1.15.0
  coverage: ^1.1.0
  dart_test_adapter: ^0.2.0
  duration: ^3.0.8
  freezed_annotation: ^1.1.0
  melos: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.0
  pubspec: ^2.0.1
  riverpod: 2.0.0-dev.3
  test: ^1.17.8

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^1.1.1

# TODO remove before publishing
# TODO even though we use Melos build_runner doesn't have options not to do a pub check
# TODO so always fails with:
# TODO "The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "dart pub get" again.""
dependency_overrides:
  dart_test_adapter:
    path: ../dart_test_adapter

executables:
  spec: main
