name: spec_cli
version: 0.1.2+2
description: CLI for Spec - a streamlined testing framework for Dart & Flutter.
homepage: "https://github.com/invertase/spec"

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.2+1
  args: ^2.3.1
  cli_util: ^0.3.5
  collection: ^1.16.0
  coverage: ^1.6.1
  dart_test_adapter: ^0.2.0
  duration: ^3.0.8
  freezed_annotation: ^2.1.0
  melos: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.0
  pubspec: ^2.0.1
  riverpod: ^2.0.2
  test: ^1.17.8

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^2.1.1

executables:
  spec: main
