name: spec_cli
version: 0.1.0

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.1
  args: ^2.1.1
  cli_util: ^0.3.0
  collection: ^1.15.0
  dart_test_adapter: ^0.1.0
  duration: ^3.0.8
  freezed_annotation: ^1.1.0
  melos: ^1.1.2
  meta: ^1.7.0
  path: ^1.8.0
  pubspec: ^2.0.1
  riverpod: ^2.0.0-dev.0
  test: ^1.17.8

# TODO remove before publishing
dependency_overrides:
  dart_test_adapter:
    path: ../dart_test_adapter

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^1.1.1

executables:
  spec: main
