name: all_packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Analyze"
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Check formatting"
        run: melos run format-check

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Run Tests"
        run: melos run test --no-select

  test_macos:
    runs-on: macos-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Run Tests"
        run: melos run test --no-select

  test_windows:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: bluefireteam/melos-action@v2
      - name: "Run Tests"
        run: cmd \k melos run test --no-select
